/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["postSign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check user status */
        post: operations["postUserCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register user */
        post: operations["postUserRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        status: number;
                        message: string;
                        errors?: {
                            code: number;
                            message: string;
                        }[];
                        meta?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    postSign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "local" | "sso";
                    provider?: string;
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                    token?: string;
                    password?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** @enum {string} */
                    type: "local" | "sso";
                    provider?: string;
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                    token?: string;
                    password?: string;
                };
                "multipart/form-data": {
                    /** @enum {string} */
                    type: "local" | "sso";
                    provider?: string;
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                    token?: string;
                    password?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        status: number;
                        message: string;
                        errors?: {
                            code: number;
                            message: string;
                        }[];
                        meta?: {
                            [key: string]: unknown;
                        };
                    } & {
                        data: {
                            token: string;
                        };
                    };
                };
            };
        };
    };
    postUserCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    id?: string;
                    username?: string;
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        status: number;
                        message: string;
                        errors?: {
                            code: number;
                            message: string;
                        }[];
                        meta?: {
                            [key: string]: unknown;
                        };
                    } & {
                        data: {
                            registered: boolean;
                        };
                    };
                };
            };
        };
    };
    postUserRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id?: string;
                    name: string;
                    username?: string | null;
                    /** Format: email */
                    email: string;
                    password: string;
                    avatar?: string | null;
                    bio?: string;
                    phone?: string;
                    location?: string;
                    /** @enum {string} */
                    status: "active" | "banned";
                };
                "application/x-www-form-urlencoded": {
                    id?: string;
                    name: string;
                    username?: string | null;
                    /** Format: email */
                    email: string;
                    password: string;
                    avatar?: string | null;
                    bio?: string;
                    phone?: string;
                    location?: string;
                    /** @enum {string} */
                    status: "active" | "banned";
                };
                "multipart/form-data": {
                    id?: string;
                    name: string;
                    username?: string | null;
                    /** Format: email */
                    email: string;
                    password: string;
                    avatar?: string | null;
                    bio?: string;
                    phone?: string;
                    location?: string;
                    /** @enum {string} */
                    status: "active" | "banned";
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        status: number;
                        message: string;
                        errors?: {
                            code: number;
                            message: string;
                        }[];
                        meta?: {
                            [key: string]: unknown;
                        };
                    } & {
                        data: {
                            id?: string;
                            name: string;
                            username?: string | null;
                            /** Format: email */
                            email: string;
                            password: string;
                            avatar?: string | null;
                            bio?: string;
                            phone?: string;
                            location?: string;
                            status: "active" | "banned";
                        };
                    };
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
                "content-type"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        status: number;
                        message: string;
                        errors?: {
                            code: number;
                            message: string;
                        }[];
                        meta?: {
                            [key: string]: unknown;
                        };
                    } & {
                        data: {
                            id?: string;
                            name: string;
                            username?: string | null;
                            /** Format: email */
                            email: string;
                            password: string;
                            avatar?: string | null;
                            bio?: string;
                            phone?: string;
                            location?: string;
                            status: "active" | "banned";
                        };
                    };
                };
            };
        };
    };
}
